### ISSUE TITLE
Where to find OpenOCDPackage and QuickSetupDatabase namespace / classes?

### ISSUE THREAD

**Issue by gojimmypi** [sysprogs/BSPTools#3]
I'm interested in the ESP8266DebugPackage ESPImageTool, however when I attempt to build it, Visual Studio complains that:

Error	CS0246	The type or namespace name 'OpenOCDPackage' could not be found (are you missing a using directive or an assembly reference?)

Error	CS0246	The type or namespace name 'QuickSetupDatabase' could not be found (are you missing a using directive or an assembly reference?)	 

Error	CS0246	The type or namespace name 'CommandTestForm' could not be found (are you missing a using directive or an assembly reference?)	

Error	CS0103	The name 'UsbDriverHelper' does not exist in the current context	ESP8266DebugPackage

Error	CS0103	The name 'UsbProgrammerSelectionForm' does not exist in the current context	ESP8266DebugPackage

additionally, this code fails with Error CS1579 foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for GetEnumerator   (ifaces)C:\workspace\BSPTools\DebugPackages\ESP8266DebugPackage\OpenOCDDebugConfigurator.cs	52	

```
            var ifaces = _QuickSetupData.AllInterfaces;
            if (ifaces != null)
                foreach (var iface in ifaces)
                    cbQuickInterface.Items.Add(iface);

            cbQuickInterface.Items.Add(new ManualIfacePseudoitem());
```

Can you help me find these missing libraries? There's no match in all of GitHub for instance of 'OpenOCDPackage'

**Comment by sysprogs** [comment]
Hi,
You can get the OpenOCDPackage.dll by installing OpenOCD via Tools->VisualGDB Package Manager. Then simply add a reference to %LOCALAPPDATA%\VisualGDB\EmbeddedDebugPackages\com.sysprogs.arm.openocd\OpenOCDPackage.dll and you should be able to build the ESPImageTool and the related libraries.

**Comment by gojimmypi** [comment]
Although I have the OpenOCDPackage.dll I still have a couple of unresolved errors when compiling:

```
Error	CS0006	Metadata file 'C:\workspace\BSPTools\DebugPackages\ESP8266DebugPackage\bin\Debug\ESP8266DebugPackage.dll' could not be found	ESPImageTool	C:\workspace\BSPTools\DebugPackages\ESP8266DebugPackage\ESPImageTool\CSC	1	Active
Error	CS0122	'UsbDriverHelper' is inaccessible due to its protection level	ESP8266DebugPackage	C:\workspace\BSPTools\DebugPackages\ESP8266DebugPackage\OpenOCDDebugConfigurator.cs	249	Active

```
The error occurs in OpenOCDDebugConfigurator, line 249 on UsbDriverHelper:

```
if (!UsbDriverHelper.TryCheckDeviceAndInstallDriversInteractively(iface.UsbIdentities, iface.UniversalDriverId))
```
which is curious that it is a protection level complaint, in that the meta data file generated looks like this:

```
#region Assembly OpenOCDPackage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\gojimmypi\AppData\Local\VisualGDB\EmbeddedDebugPackages\com.sysprogs.arm.openocd\OpenOCDPackage.dll
#endregion

namespace OpenOCDPackage
{
    internal class UsbDriverHelper
    {
        public UsbDriverHelper();

        public static bool TryCheckDeviceAndInstallDriversInteractively(QuickSetupDatabase.UsbIdentity[] usbIdentities, string universalDriverId);
        public static global::UsbDriverTool.DeviceRecord TryFindDeviceInstance(QuickSetupDatabase.UsbIdentity[] usbIdentities);
    }
}
```

It is also slightly different menu: Tools -> Manage VisualGDB Packages (different Visual Studio version? I am using 2015)

The package is labeled "20161025" and I did a refresh so the file date is as of today... but same error.

**Comment by sysprogs** [comment]
Sorry about that, looks like the latest public OpenOCDPackage release is missing one small change.
Please try this version: http://sysprogs.com/files/tmp/OpenOCDPackage.dll

**Comment by ela34** [comment]
Seems the version in the previous post is no more available and the issue has not been fixed in the currently available package. Can you update/fix the link above?

**Comment by sysprogs** [comment]
No problem, here's the latest version of the package:
[OpenOCDPackage.zip](https://github.com/sysprogs/BSPTools/files/1043676/OpenOCDPackage.zip)
