### ISSUE TITLE
BSP File Specifications and Pre/Post Build Steps

### ISSUE THREAD

**Issue by whinis** [sysprogs/BSPTools#6]
Hello, I was wondering if there is a published set of fields allowed within the BSP files?
Also related to this as I could not find it in the source files. Is there a way to specify Pre and Post build steps within a BSP file ?

**Comment by sysprogs** [comment]
The BSP files contain snapshots of .Net classes inside BSPEngine.dll, so you can get an exhaustive list of fields by opening any of the BSP generators and going to definition of types like **BoardSupportPackage**.

If you would like to specify pre- and post-build steps, please consider looking into [project templates](https://visualgdb.com/tutorials/arm/templates/) instead.
