### ISSUE TITLE
RegexTransform patch not working

### ISSUE THREAD

**Issue by wtywtykk** [sysprogs/BSPTools#7]
Hi, there seems a problem with RegexTransform patch, the ValueFormat attribute is actually not used. So I can't apply patches with RegexTransform.

The problem is at BSPTools/libraries/BSPGenerationTools/SourceCopyTools.cs line 181

`lines[i] = string.Format(lines[i], args.ToArray());`

but I think it should be

`lines[i] = string.Format(ValueFormat, args.ToArray());`

**Comment by sysprogs** [comment]
Thanks, we have fixed it in https://github.com/sysprogs/BSPTools/commit/1190ce2356d1ff336dca981994396c31dbe7f184
